In [1]:
import geopandas as gpd
import pandas as pd

In [4]:
df = pd.read_csv("Data/R13283898_SL140.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head(3)

,Geo_FIPS,Geo_QName,Geo_FILEID,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_PUMA5,Geo_PUMA1,Geo_GEOID,Geo_NAME,Geo_BTTR,Geo_BTBG,Geo_PLACESE,SE_A13004_001,SE_A13004_002,SE_A13004_003,SE_A13004_004,SE_A13004_005,SE_A13004_006,SE_A13004_007
0,6037101110,"Census Tract 1011.10, Los Angeles County, Cali...",ACSSF,ca,140,0,4200,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101110,Census Tract 1011.10,NaN,NaN,NaN,3806,234,57,145,240,212,2918
1,6037101122,"Census Tract 1011.22, Los Angeles County, Cali...",ACSSF,ca,140,0,4201,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101122,Census Tract 1011.22,NaN,NaN,NaN,4216,170,15,75,123,155,3678
2,6037101220,"Census Tract 1012.20, Los Angeles County, Cali...",ACSSF,ca,140,0,4202,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101220,Census Tract 1012.20,NaN,NaN,NaN,3583,120,363,167,237,306,2390

In [9]:
df2 = pd.read_csv("Data/R13283899_SL140.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df2.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2498 entries, 0 to 2497
Data columns (total 120 columns):
 #    Column                Non-Null Count  Dtype
---   ------                --------------  -----
 0    Geo_FIPS              2498 non-null   int64
 1    Geo_QName             2498 non-null   object
 2    Geo_FILEID            2498 non-null   object
 3    Geo_STUSAB            2498 non-null   object
 4    Geo_SUMLEV            2498 non-null   int64
 5    Geo_GEOCOMP           2498 non-null   int64
 6    Geo_LOGRECNO          2498 non-null   int64
 7    Geo_US                0 non-null      float64
 8    Geo_REGION            0 non-null      float64
 9    Geo_DIVISION          0 non-null      float64
 10   Geo_STATECE           0 non-null      float64
 11   Geo_STATE             2498 non-null   int64
 12   Geo_COUNTY            2498 non-null   int64
 13   Geo_COUSUB            0 non-null      float64
 14   Geo_PLACE             0 non-null      float64
 15   Geo_TRACT             2498 non-null   int64
 16   Geo_BLKGRP            0 non-null      float64
 17   Geo_CONCIT            0 non-null      float64
 18   Geo_AIANHH            0 non-null      float64
 19   Geo_AIANHHFP          0 non-null      float64
 20   Geo_AIHHTLI           0 non-null      float64
 21   Geo_AITSCE            0 non-null      float64
 22   Geo_AITS              0 non-null      float64
 23   Geo_ANRC              0 non-null      float64
 24   Geo_CBSA              0 non-null      float64
 25   Geo_CSA               0 non-null      float64
 26   Geo_METDIV            0 non-null      float64
 27   Geo_MACC              0 non-null      float64
 28   Geo_MEMI              0 non-null      float64
 29   Geo_NECTA             0 non-null      float64
 30   Geo_CNECTA            0 non-null      float64
 31   Geo_NECTADIV          0 non-null      float64
 32   Geo_UA                0 non-null      float64
 33   Geo_UACP              0 non-null      float64
 34   Geo_CDCURR            0 non-null      float64
 35   Geo_SLDU              0 non-null      float64
 36   Geo_SLDL              0 non-null      float64
 37   Geo_VTD               0 non-null      float64
 38   Geo_ZCTA3             0 non-null      float64
 39   Geo_ZCTA5             0 non-null      float64
 40   Geo_SUBMCD            0 non-null      float64
 41   Geo_SDELM             0 non-null      float64
 42   Geo_SDSEC             0 non-null      float64
 43   Geo_SDUNI             0 non-null      float64
 44   Geo_UR                0 non-null      float64
 45   Geo_PCI               0 non-null      float64
 46   Geo_TAZ               0 non-null      float64
 47   Geo_UGA               0 non-null      float64
 48   Geo_PUMA5             0 non-null      float64
 49   Geo_PUMA1             0 non-null      float64
 50   Geo_GEOID             2498 non-null   object
 51   Geo_NAME              2498 non-null   object
 52   Geo_BTTR              0 non-null      float64
 53   Geo_BTBG              0 non-null      float64
 54   Geo_PLACESE           0 non-null      float64
 55   SE_A10003_001         2469 non-null   float64
 56   SE_A10002B_001        2498 non-null   int64
 57   SE_A10002B_002        2498 non-null   int64
 58   SE_A10002B_003        2498 non-null   int64
 59   SE_A10002B_004        2498 non-null   int64
 60   SE_A10002B_005        2498 non-null   int64
 61   SE_A10002B_006        2498 non-null   int64
 62   SE_A10002B_007        2498 non-null   int64
 63   SE_A10002B_008        2498 non-null   int64
 64   ACS21_5yr_B25009001   2498 non-null   int64
 65   ACS21_5yr_B25009002   2498 non-null   int64
 66   ACS21_5yr_B25009003   2498 non-null   int64
 67   ACS21_5yr_B25009004   2498 non-null   int64
 68   ACS21_5yr_B25009005   2498 non-null   int64
 69   ACS21_5yr_B25009006   2498 non-null   int64
 70   ACS21_5yr_B25009007   2498 non-null   int64
 71   ACS21_5yr_B25009008   2498 non-null   int64
 72   ACS21_5yr_B25009009   2498 non-null   int64
 73   ACS21_5yr_B25009010   2498 non-null   int64
 74   ACS21_5yr_B25009011   2498 non-null   int64
 75   ACS21_5yr_B25009012   2498 non-null   int64
 76   ACS21_5yr_B25009013   2498 non-null   int64
 77   ACS21_5yr_B25009014   2498 non-null   int64
 78   ACS21_5yr_B25009015   2498 non-null   int64
 79   ACS21_5yr_B25009016   2498 non-null   int64
 80   ACS21_5yr_B25009017   2498 non-null   int64
 81   ACS21_5yr_B25009001s  2498 non-null   float64
 82   ACS21_5yr_B25009002s  2498 non-null   float64
 83   ACS21_5yr_B25009003s  2498 non-null   float64
 84   ACS21_5yr_B25009004s  2498 non-null   float64
 85   ACS21_5yr_B25009005s  2498 non-null   float64
 86   ACS21_5yr_B25009006s  2498 non-null   float64
 87   ACS21_5yr_B25009007s  2498 non-null   float64
 88   ACS21_5yr_B25009008s  2498 non-null   float64
 89   ACS21_5yr_B25009009s  2498 non-null   float64
 90   ACS21_5yr_B25009010s  2498 non-null   float64
 91   ACS21_5yr_B25009011s  2498 non-null   float64
 92   ACS21_5yr_B25009012s  2498 non-null   float64
 93   ACS21_5yr_B25009013s  2498 non-null   float64
 94   ACS21_5yr_B25009014s  2498 non-null   float64
 95   ACS21_5yr_B25009015s  2498 non-null   float64
 96   ACS21_5yr_B25009016s  2498 non-null   float64
 97   ACS21_5yr_B25009017s  2498 non-null   float64
 98   ACS21_5yr_B19019001   2451 non-null   float64
 99   ACS21_5yr_B19019002   1927 non-null   float64
 100  ACS21_5yr_B19019003   2287 non-null   float64
 101  ACS21_5yr_B19019004   2133 non-null   float64
 102  ACS21_5yr_B19019005   2046 non-null   float64
 103  ACS21_5yr_B19019006   1629 non-null   float64
 104  ACS21_5yr_B19019007   842 non-null    float64
 105  ACS21_5yr_B19019008   758 non-null    float64
 106  ACS21_5yr_B19019001s  2444 non-null   float64
 107  ACS21_5yr_B19019002s  1921 non-null   float64
 108  ACS21_5yr_B19019003s  2270 non-null   float64
 109  ACS21_5yr_B19019004s  2068 non-null   float64
 110  ACS21_5yr_B19019005s  1926 non-null   float64
 111  ACS21_5yr_B19019006s  1495 non-null   float64
 112  ACS21_5yr_B19019007s  801 non-null    float64
 113  ACS21_5yr_B19019008s  727 non-null    float64
 114  ACS21_5yr_B25010001   2469 non-null   float64
 115  ACS21_5yr_B25010002   2418 non-null   float64
 116  ACS21_5yr_B25010003   2467 non-null   float64
 117  ACS21_5yr_B25010001s  2469 non-null   float64
 118  ACS21_5yr_B25010002s  2418 non-null   float64
 119  ACS21_5yr_B25010003s  2467 non-null   float64
dtypes: float64(83), int64(32), object(5)
memory usage: 2.3+ MB

In [10]:
df2.head(3)

,Geo_FIPS,Geo_QName,Geo_FILEID,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_PUMA5,Geo_PUMA1,Geo_GEOID,Geo_NAME,Geo_BTTR,Geo_BTBG,Geo_PLACESE,SE_A10003_001,SE_A10002B_001,SE_A10002B_002,SE_A10002B_003,SE_A10002B_004,SE_A10002B_005,SE_A10002B_006,SE_A10002B_007,SE_A10002B_008,ACS21_5yr_B25009001,ACS21_5yr_B25009002,ACS21_5yr_B25009003,ACS21_5yr_B25009004,ACS21_5yr_B25009005,ACS21_5yr_B25009006,ACS21_5yr_B25009007,ACS21_5yr_B25009008,ACS21_5yr_B25009009,ACS21_5yr_B25009010,ACS21_5yr_B25009011,ACS21_5yr_B25009012,ACS21_5yr_B25009013,ACS21_5yr_B25009014,ACS21_5yr_B25009015,ACS21_5yr_B25009016,ACS21_5yr_B25009017,ACS21_5yr_B25009001s,ACS21_5yr_B25009002s,ACS21_5yr_B25009003s,ACS21_5yr_B25009004s,ACS21_5yr_B25009005s,ACS21_5yr_B25009006s,ACS21_5yr_B25009007s,ACS21_5yr_B25009008s,ACS21_5yr_B25009009s,ACS21_5yr_B25009010s,ACS21_5yr_B25009011s,ACS21_5yr_B25009012s,ACS21_5yr_B25009013s,ACS21_5yr_B25009014s,ACS21_5yr_B25009015s,ACS21_5yr_B25009016s,ACS21_5yr_B25009017s,ACS21_5yr_B19019001,ACS21_5yr_B19019002,ACS21_5yr_B19019003,ACS21_5yr_B19019004,ACS21_5yr_B19019005,ACS21_5yr_B19019006,ACS21_5yr_B19019007,ACS21_5yr_B19019008,ACS21_5yr_B19019001s,ACS21_5yr_B19019002s,ACS21_5yr_B19019003s,ACS21_5yr_B19019004s,ACS21_5yr_B19019005s,ACS21_5yr_B19019006s,ACS21_5yr_B19019007s,ACS21_5yr_B19019008s,ACS21_5yr_B25010001,ACS21_5yr_B25010002,ACS21_5yr_B25010003,ACS21_5yr_B25010001s,ACS21_5yr_B25010002s,ACS21_5yr_B25010003s
0,6037101110,"Census Tract 1011.10, Los Angeles County, Cali...",ACSSF,ca,140,0,4200,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101110,Census Tract 1011.10,NaN,NaN,NaN,2.54,644,200,234,86,97,21,6,0,1494,850,135,238,329,108,35,5,0,644,200,234,86,97,21,6,0,74.54546,81.21212,39.39394,50.90909,67.27273,43.63636,26.666670,5.454545,7.878788,72.72727,49.09091,50.30303,39.39394,33.33333,20.00000,7.272727,7.878788,68529.0,30625.0,92500.0,57271.0,98839.0,188125.0,NaN,NaN,17158.181818,13578.181818,28305.454545,21747.272727,16249.090909,73952.727273,NaN,NaN,2.54,2.66,2.38,0.127273,0.133333,0.206061
1,6037101122,"Census Tract 1011.22, Los Angeles County, Cali...",ACSSF,ca,140,0,4201,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101122,Census Tract 1011.22,NaN,NaN,NaN,3.09,344,116,43,48,36,24,77,0,1372,1028,173,359,147,252,8,60,29,344,116,43,48,36,24,77,0,101.21210,61.21212,45.45454,51.51515,43.63636,48.48485,7.878788,30.909090,24.242420,106.66670,66.06061,27.87879,28.48485,26.66667,23.63636,72.121220,7.878788,108198.0,50417.0,130769.0,NaN,107222.0,NaN,135601.0,NaN,15108.484848,28315.757576,13844.242424,NaN,52390.909091,NaN,24092.121212,NaN,3.09,3.04,3.24,0.248485,0.200000,0.800000
2,6037101220,"Census Tract 1012.20, Los Angeles County, Cali...",ACSSF,ca,140,0,4202,NaN,NaN,NaN,NaN,6,37,NaN,NaN,101220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US06037101220,Census Tract 1012.20,NaN,NaN,NaN,2.64,762,261,256,71,63,80,14,17,1357,595,171,145,120,92,56,11,0,762,261,256,71,63,80,14,17,121.81820,101.81820,92.12122,39.39394,35.75758,33.93939,22.424240,10.303030,7.878788,96.96970,46.06061,80.60606,29.09091,30.30303,40.00000,12.727270,15.757580,59119.0,37500.0,58958.0,86083.0,79688.0,90441.0,NaN,NaN,5581.818182,12576.969697,4719.393939,31000.606061,38788.484848,18956.363636,NaN,NaN,2.64,2.83,2.49,0.175758,0.357576,0.212121

In [11]:
df2['SE_A10003_001'].describe()

count    2469.000000
mean        3.058429
std         0.769966
min         1.050000
25%         2.530000
50%         3.010000
75%         3.590000
max         7.760000
Name: SE_A10003_001, dtype: float64